name: anime-default
description: Default configuration targeting anime-style characters with AI-driven layering and rigging.
segmentation:
  backend: sam-hq-local
  num_segments: 18
  compactness: 8.0
  min_area_px: 2048
  feather_radius: 2
  sam_hq_local_model_id: syscv-community/sam-hq-vit-base
  sam_hq_local_device: null
  sam_hq_local_score_threshold: 0.2
export:
  psd:
    enabled: true
    group_name: CubiAI Layers
  live2d:
    enabled: true
    texture_size: 2048
    padding: 24
    background_color: [0, 0, 0, 0]
rigging:
  template: humanoid-basic
  idle_motion: true
  blink_parameters:
    - ParamEyeLOpen
    - ParamEyeROpen
  strategy: llm
  llm_model: gpt-4.1-mini
  llm_base_url: https://api.openai.com/v1
  llm_api_key_env: OPENAI_API_KEY
  builder:
    # Install the Live2D Cubism command line exporter and expose it via $CUBISM_CLI.
    command:
      - "${CUBISM_CLI}"
      - "--psd"
      - "{PSD_PATH}"
      - "--rig-config"
      - "{RIG_JSON}"
      - "--output"
      - "{OUTPUT_DIR}"
    timeout_seconds: 900
models:
  assets: []
metadata:
  created_by: CubiAI
  notes: Default configuration generated during scaffolding.
