name: anime-default
description: Default configuration targeting anime-style characters with AI-driven layering and rigging.
segmentation:
  backend: sam-hq-local
  num_segments: 18
  compactness: 8.0
  min_area_px: 2048
  feather_radius: 2
  sam_hq_local_model_id: syscv-community/sam-hq-vit-base
  sam_hq_local_device: null
  sam_hq_local_score_threshold: 0.2
export:
  psd:
    enabled: true
    group_name: CubiAI Layers
  png:
    enabled: true
  live2d:
    enabled: false
    texture_size: 2048
    padding: 24
    background_color: [0, 0, 0, 0]
rigging:
  enabled: false
annotation:
  llm:
    enabled: false
    model: gpt-5
    base_url: null
    api_key_env: OPENAI_API_KEY
    temperature: 0.2
    max_output_tokens: 1024
    timeout_seconds: 180
    prompt_template: null
models:
  assets: []
metadata:
  created_by: CubiAI
  notes: Default configuration generated during scaffolding.
